version: '1.0'
name: pipeline-20220610
displayName: pipeline-20220610
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: stage-700245dd
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          # 请在此输入您想执行的脚本
          echo 'Hello Gitee!'
          curl -X GET https://service-cbeqp2zl-1253286983.bj.apigw.tencentcs.com/release/helloworld-1654766618
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
